
document.writeln("<div>");
document.writeln("<div class=\'container-fluid box12\'>");
document.writeln("    <div class=\'container\'>");
document.writeln("        <div class=\'box12-a\'>");
document.writeln("");
document.writeln("            <div class=\'box12-aa box12-a1\'>");
document.writeln("                <br>技能树 — 改变你我");
document.writeln("                <br>");
document.writeln("                <br>");
document.writeln("");
document.writeln("                <br> 关于我们 | 联系我们 | 合作企业");
document.writeln("            </div>");
document.writeln("            <div class=\'box12-aa box12-a2\'>");
document.writeln("                <br>旗下网站");
document.writeln("                <br>");
document.writeln("                <br><em class=\'gg\'>草船云孵化器</em> 最强IT特训营");
document.writeln("                <br>");
document.writeln("                <br>葡萄藤轻游戏 桌游精灵");
document.writeln("            </div>");
document.writeln("");
document.writeln("            <div class=\'box12-aa box12-a3\'>");
document.writeln("                <div class=\'box12-tt\'>");
document.writeln("                    <br>微信公众平台");
document.writeln("                    <div class=\'codebar\'></div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</div>");
document.writeln("<div class=\'footer\'>Copyright©2015技能树 www.jnshu.com All Rights Reserved 京ICP备13005880号</div>");
document.writeln("");
document.writeln("</div>");
