

document.writeln("<div>");
document.writeln("<div class=\'container-fluid box1\'>");
document.writeln("    <div class=\'container box1-1\'>");
document.writeln("        客服热线：010-594-78634");
document.writeln("        <div class=\'box1-a1\'></div>");
document.writeln("        <div class=\'box1-a2\'></div>");
document.writeln("        <div class=\'box1-a3\'></div>");
document.writeln("    </div>");
document.writeln("</div>");
document.writeln("");
document.writeln("<nav class=\'navbar navbar-expand-md bg-green navbar-light\'>");
document.writeln("    <div class=\'container\'>");
document.writeln("        <div class=\'wwwjnsucom\'></div>");
document.writeln("        <button class=\'navbar-toggler\' type=\'button\' data-toggle=\'collapse\' data-target=\'#collapsibleNavbar\'>");
document.writeln("            <span class=\'navbar-toggler-icon\'></span>");
document.writeln("        </button>");
document.writeln("        <div class=\'collapse navbar-collapse\' id=\'collapsibleNavbar\'>");
document.writeln("            <ul class=\'navbar-nav\'>");
document.writeln("                <li class=\'nav-item\'>");
document.writeln("                    <a class=\'nav-link\' href=\'../html/task9-index.html\'>首页</a>");
document.writeln("                </li>");
document.writeln("                <li class=\'nav-item\'>");
document.writeln("                    <a class=\'nav-link\' href=\'../html/task9-2.html\'>职业</a>");
document.writeln("                </li>");
document.writeln("                <li class=\'nav-item\'>");
document.writeln("                    <a class=\'nav-link\' href=\'../html/task9-1.html\'>推荐</a>");
document.writeln("                </li>");
document.writeln("                <li class=\'nav-item\'>");
document.writeln("                    <a class=\'nav-link\' href=\'#\'>关于</a>");
document.writeln("                </li>");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</nav>");
document.writeln("");
document.writeln("");
document.writeln("</div>");
